### PR TITLE
Add Support for Export and Import of Credentials

### PR DESCRIPTION
**Pull request by tmulkern**
* Created PortableCredential struct
* func ToCredential() to create Credential from PortableCredential
* func ExportToPortableCredential() to create PortalCredential from Credential

* Updated import_test
* Added export_test

## Description
This is an improvement to my earlier PR, this is allows for Import and Exporting the credential. I have updated existing tests and created ones for export cases. I am open to any design changes/suggestions

## Must
- [X ] Tests
- [ ] Documentation (if applicable)

### CODE REVIEW

**Comment by shilgapira** [comment]
Hi! Thanks for your contribution again!

I'll go over the changes and ping you back 👍

**Comment by shilgapira** [comment]
This is a really cool idea.

I'd like to find a way to support this use case (exporting/importing) without adding another struct `PortableCredential`. If it's okay with you I can merge this PR now and then refactor to combine the `Credential` and `PortableCredential` structs somehow.

**Comment by tmulkern** [comment]
Yes, please merge away. I am not happy with the two structs solution either.

**Comment by shilgapira** [comment]
Great, thanks! 👍

**Review by shilgapira — APPROVED** [review]

**Pull request merged**
